### PR TITLE
Fix issue 33 (response missing after going to a different page)

### LINKED ISSUE #33: response missing after going to a different page
if I go to the second problem, and then click back to the first problem, it looks like my answers have been deleted. If I hard-refresh the page, I get back to the answer state.

### PR DESCRIPTION
**Pull request by richardtape**
This adds a new `get_data` XBlock JSON Handler which returns the persisted data saved by the student. This allows us to verify the persisted data if the student moves back and forth through the steps in the same or different instances of the XBlock.

Also adds JS and Python unit tests to cover this functionality.

Fix #33

### CODE REVIEW

File: ubcpi/static/js/src/ubcpi.js [hunk 1]
```diff
@@ -98,11 +111,15 @@ angular.module('UBCPI', ['ngSanitize', 'ngCookies'])
             // all status of the app. Passed it from backend so we have a synced status codes
             self.ALL_STATUS = data.all_status;
 
-            // Assign data based on what is submitted
-            assignData(self, data);
+            // Assign data based on what has been persisted
+            var persistedDataObject = get_data().then( function(persistedData) {
+
+                if ( persistedData.answer_original !== null ) {
+                    data = persistedData;
```
Comment (xcompass) [inline ubcpi/static/js/src/ubcpi.js]: Could you remove this assignment and use persistedData directly? I don't think data is being used anywhere else. Though this assignment override the variable data defined above. It may cause confusion in the future.

**Comment by xcompass** [comment]
Thanks @richardtape everything else looks great. :+1: Once you addressed my comment, could you please squash the commits and I can merge it.
